import React from "react";

import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
};

function Layout({ children }: Props) {
  return (
    <html>
      <body
        className={`${geistMono.variable} antialiased ${geistSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}

export default Layout;
